/*
================================================================================
COURSE:     CSS171 - Computer Graphics and Visual Computing
TASK:       Practical Exam #1 (Rotating Textured 3D Castle)
FILENAME:   CSS171_PE1_Soriano.cpp
AUTHOR:     Willard Soriano
INSTRUCTOR: Polycarpio V. Cabalag II
DATE:       September 2026

DESCRIPTION:
Renders an original walled castle on a grassy island, spinning on a
turntable, with the modern OpenGL 3.3 core pipeline (GLFW + GLAD + GLM +
GLSL shaders) and six image textures loaded with stb_image.

KEY FEATURES:
1. Efficient Geometry: only THREE indexed meshes exist on the GPU - a box
   (24 vertices / 12 triangles), a cylinder and a cone. Every wall, tower,
   roof, merlon, door, window and flag is one of these meshes drawn with its
   own model matrix, so no geometry is duplicated.
2. Hierarchical Modeling: builder functions (addTower, addKeep, ...) place
   parts relative to a parent transform, and one animated root rotation
   spins the whole castle as a single unit.
3. Multiple Textures: stone, roof tiles, wood, grass, dirt and a banner
   (see textures/, generated by tools/generate_textures.py).
4. Scale-Aware Box Mapping: box faces take their texture coordinates from
   the part's real size, so bricks keep the same size on a long wall and on
   a small merlon instead of stretching.
5. Lighting: directional sunlight plus sky/ground hemisphere ambient, with
   normals transformed by each part's normal matrix.

RUN FROM THE FOLDER THAT CONTAINS textures/ so the relative paths resolve.
CONTROLS: ESC closes the window.
================================================================================
*/

#include <glad/glad.h>
#include <GLFW/glfw3.h>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>

#define STB_IMAGE_IMPLEMENTATION
#include "third_party/stb_image.h"

#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>

// ------------------------------------------------------------------------------
// Configuration
// ------------------------------------------------------------------------------

// Window specifications
const int   WINDOW_WIDTH  = 1000;
const int   WINDOW_HEIGHT = 700;
const char *WINDOW_TITLE  = "CSS171 PE1 - Rotating 3D Castle (Willard Soriano)";

// Camera: raised and pulled back so the whole island stays in frame
const float     FIELD_OF_VIEW_DEG = 45.0f;
const float     NEAR_PLANE        = 0.1f;
const float     FAR_PLANE         = 100.0f;
const glm::vec3 CAMERA_POSITION(0.0f, 6.5f, 14.0f);
const glm::vec3 CAMERA_TARGET(0.0f, 1.35f, 0.0f);
const glm::vec3 CAMERA_UP(0.0f, 1.0f, 0.0f);

// Turntable speed of the whole castle
const float ROTATION_DEGREES_PER_SECOND = 20.0f;

// Lighting (world space). Sun direction points FROM the scene TOWARD the sun.
const glm::vec3 SUN_DIRECTION(-0.45f, 0.80f, 0.40f);
const glm::vec3 SUN_COLOR(1.00f, 0.95f, 0.85f);
const glm::vec3 SKY_AMBIENT(0.42f, 0.48f, 0.60f);
const glm::vec3 GROUND_AMBIENT(0.26f, 0.24f, 0.20f);

// Background: clear daytime sky
const glm::vec3 SKY_COLOR(0.53f, 0.74f, 0.92f);

// Texture density for box-mapped parts: texture repeats per world unit
const float TEXTURE_REPEATS_PER_UNIT = 0.9f;

// Mesh tessellation for round parts
const int ROUND_SEGMENTS = 32;

// Castle dimensions (world units; ground surface is at y = 0)
const float ISLAND_RADIUS     = 5.6f;  // round island: silhouette is constant while spinning
const float WALL_HALF_SPAN    = 3.0f;  // towers sit at (+-span, +-span)
const float WALL_HEIGHT       = 1.8f;
const float WALL_THICKNESS    = 0.5f;
const float TOWER_RADIUS      = 0.75f;
const float TOWER_HEIGHT      = 2.8f;
const float TOWER_ROOF_RADIUS = 0.95f;
const float TOWER_ROOF_HEIGHT = 1.4f;
const float KEEP_WIDTH        = 2.4f;
const float KEEP_HEIGHT       = 3.2f;
const float MERLON_SIZE       = 0.32f;
const float MERLON_HEIGHT     = 0.35f;
const float MERLON_SPACING    = 0.62f;

// ------------------------------------------------------------------------------
// Shaders
// ------------------------------------------------------------------------------

const char *VERTEX_SHADER_SOURCE = R"(
#version 330 core
layout (location = 0) in vec3 aPosition;
layout (location = 1) in vec3 aNormal;
layout (location = 2) in vec2 aTexCoord;

uniform mat4 uModel;
uniform mat3 uNormalMatrix;
uniform mat4 uView;
uniform mat4 uProjection;

// Texture coordinate mode: mesh UVs scaled by uTexScale, or box mapping
uniform bool  uBoxMapping;
uniform vec3  uPartSize;       // world-space size of the part (box mapping)
uniform float uRepeatsPerUnit; // texture repeats per world unit (box mapping)
uniform vec2  uTexScale;       // UV multiplier (mesh UV mode)

out vec3 vWorldNormal;
out vec2 vTexCoord;

void main() {
    gl_Position  = uProjection * uView * uModel * vec4(aPosition, 1.0);
    vWorldNormal = normalize(uNormalMatrix * aNormal);

    if (uBoxMapping) {
        // Project the face onto the two axes it spans, measured in world
        // units, so the texture keeps a constant size on any box.
        vec3 sized = aPosition * uPartSize * uRepeatsPerUnit;
        vec3 n = abs(aNormal);
        if (n.x > 0.5)      vTexCoord = sized.zy;   // side faces facing +-X
        else if (n.z > 0.5) vTexCoord = sized.xy;   // side faces facing +-Z
        else                vTexCoord = sized.xz;   // top and bottom faces
    } else {
        vTexCoord = aTexCoord * uTexScale;
    }
}
)";

const char *FRAGMENT_SHADER_SOURCE = R"(
#version 330 core
in vec3 vWorldNormal;
in vec2 vTexCoord;

uniform sampler2D uTexture;
uniform vec3 uTint;
uniform vec3 uSunDirection;
uniform vec3 uSunColor;
uniform vec3 uSkyAmbient;
uniform vec3 uGroundAmbient;

out vec4 FragColor;

void main() {
    vec3 normal = normalize(vWorldNormal);

    // Hemisphere ambient: upward faces catch sky light, downward faces
    // catch bounce light from the ground.
    vec3 ambient = mix(uGroundAmbient, uSkyAmbient, normal.y * 0.5 + 0.5);
    float diffuse = max(dot(normal, normalize(uSunDirection)), 0.0);

    vec3 albedo = texture(uTexture, vTexCoord).rgb * uTint;
    FragColor = vec4(albedo * (ambient + diffuse * uSunColor), 1.0);
}
)";

// ------------------------------------------------------------------------------
// Data types
// ------------------------------------------------------------------------------

// Interleaved vertex layout shared by all meshes
struct Vertex {
    glm::vec3 position;
    glm::vec3 normal;
    glm::vec2 texCoord;
};

// One indexed mesh on the GPU
struct Mesh {
    GLuint  vao        = 0;
    GLuint  vbo        = 0;
    GLuint  ebo        = 0;
    GLsizei indexCount = 0;
};

// Which of the three shared meshes a part uses
enum class Shape { Box, Cylinder, Cone };

// Every texture the castle uses; the order matches TEXTURE_FILES
enum TextureId { TEX_STONE, TEX_ROOF, TEX_WOOD, TEX_GRASS, TEX_DIRT, TEX_BANNER, TEXTURE_COUNT };

struct TextureFile {
    const char *path;
    GLint       wrapMode; // GL_REPEAT for tiling, GL_CLAMP_TO_EDGE for decals
};

const TextureFile TEXTURE_FILES[TEXTURE_COUNT] = {
    { "textures/stone.png",  GL_REPEAT },
    { "textures/roof.png",   GL_REPEAT },
    { "textures/wood.png",   GL_REPEAT },
    { "textures/grass.png",  GL_REPEAT },
    { "textures/dirt.png",   GL_REPEAT },
    { "textures/banner.png", GL_CLAMP_TO_EDGE },
};

// One drawable piece of the castle, positioned relative to the castle root
struct Part {
    Shape     shape;
    TextureId texture;
    glm::mat4 transform;             // castle-space placement, rotation and size
    glm::vec3 size;                  // world size, used by box mapping
    glm::vec3 tint;                  // multiplies the texture color
    bool      boxMapping;            // true: size-aware UVs; false: mesh UVs
    glm::vec2 texScale;              // UV multiplier when boxMapping is false
};

const glm::vec3 NO_TINT(1.0f);

// ------------------------------------------------------------------------------
// Mesh construction
// ------------------------------------------------------------------------------

// Upload vertices and indices into a new VAO/VBO/EBO
Mesh uploadMesh(const std::vector<Vertex> &vertices, const std::vector<unsigned int> &indices) {
    Mesh mesh;
    mesh.indexCount = (GLsizei)indices.size();

    glGenVertexArrays(1, &mesh.vao);
    glGenBuffers(1, &mesh.vbo);
    glGenBuffers(1, &mesh.ebo);

    glBindVertexArray(mesh.vao);
    glBindBuffer(GL_ARRAY_BUFFER, mesh.vbo);
    glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(Vertex), vertices.data(), GL_STATIC_DRAW);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, mesh.ebo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), indices.data(), GL_STATIC_DRAW);

    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void *)offsetof(Vertex, position));
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void *)offsetof(Vertex, normal));
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void *)offsetof(Vertex, texCoord));
    glEnableVertexAttribArray(2);

    glBindVertexArray(0);
    return mesh;
}

// Unit box centered on the origin: 6 faces x 4 vertices = 24 vertices,
// 12 triangles. Faces need their own vertices because each corner has a
// different normal and texture coordinate on each of its three faces.
Mesh createBoxMesh() {
    struct Face {
        glm::vec3 normal;
        glm::vec3 right; // along the face's texture U axis
        glm::vec3 up;    // along the face's texture V axis; right x up = normal
    };
    const Face faces[] = {
        { { 1, 0, 0 }, { 0, 0, -1 }, { 0, 1, 0 } },
        { { -1, 0, 0 }, { 0, 0, 1 }, { 0, 1, 0 } },
        { { 0, 1, 0 }, { 1, 0, 0 }, { 0, 0, -1 } },
        { { 0, -1, 0 }, { 1, 0, 0 }, { 0, 0, 1 } },
        { { 0, 0, 1 }, { 1, 0, 0 }, { 0, 1, 0 } },
        { { 0, 0, -1 }, { -1, 0, 0 }, { 0, 1, 0 } },
    };
    const glm::vec2 corners[] = { { 0, 0 }, { 1, 0 }, { 1, 1 }, { 0, 1 } };

    std::vector<Vertex>       vertices;
    std::vector<unsigned int> indices;
    for (const Face &face : faces) {
        unsigned int first = (unsigned int)vertices.size();
        for (const glm::vec2 &corner : corners) {
            glm::vec3 position = face.normal * 0.5f + face.right * (corner.x - 0.5f) + face.up * (corner.y - 0.5f);
            vertices.push_back({ position, face.normal, corner });
        }
        // Counter-clockwise seen from outside because right x up = normal
        indices.insert(indices.end(), { first, first + 1, first + 2, first + 2, first + 3, first });
    }
    return uploadMesh(vertices, indices);
}

// Cylinder of radius 0.5 from y = 0 to y = 1, with a top cap (the bottom
// always rests on something, so it is never visible and is omitted).
Mesh createCylinderMesh(int segments) {
    std::vector<Vertex>       vertices;
    std::vector<unsigned int> indices;
    const float TWO_PI = 6.28318530718f;

    // Side: one bottom/top vertex pair per segment edge; the seam column is
    // duplicated (segments + 1 columns) so U can run cleanly from 0 to 1.
    for (int i = 0; i <= segments; ++i) {
        float u = (float)i / segments;
        float angle = u * TWO_PI;
        glm::vec3 normal(std::cos(angle), 0.0f, std::sin(angle));
        vertices.push_back({ normal * 0.5f, normal, { u, 0.0f } });
        vertices.push_back({ normal * 0.5f + glm::vec3(0, 1, 0), normal, { u, 1.0f } });
    }
    for (int i = 0; i < segments; ++i) {
        unsigned int bottom0 = 2 * i, top0 = bottom0 + 1, bottom1 = bottom0 + 2, top1 = bottom0 + 3;
        indices.insert(indices.end(), { bottom0, top0, top1, bottom0, top1, bottom1 });
    }

    // Top cap: a fan around a center vertex
    unsigned int center = (unsigned int)vertices.size();
    vertices.push_back({ { 0, 1, 0 }, { 0, 1, 0 }, { 0.5f, 0.5f } });
    for (int i = 0; i <= segments; ++i) {
        float angle = (float)i / segments * TWO_PI;
        glm::vec2 ring(std::cos(angle), std::sin(angle));
        vertices.push_back({ { ring.x * 0.5f, 1.0f, ring.y * 0.5f }, { 0, 1, 0 }, ring * 0.5f + 0.5f });
    }
    for (int i = 0; i < segments; ++i) {
        indices.insert(indices.end(), { center, center + 2 + i, center + 1 + i });
    }
    return uploadMesh(vertices, indices);
}

// Cone of base radius 0.5 at y = 0 with its apex at y = 1, plus a base cap
// (visible from below where a roof overhangs its tower).
Mesh createConeMesh(int segments) {
    std::vector<Vertex>       vertices;
    std::vector<unsigned int> indices;
    const float TWO_PI = 6.28318530718f;
    const float RADIUS = 0.5f;
    const float HEIGHT = 1.0f;

    // Slanted side normal: perpendicular to the slope, (cos*h, r, sin*h)
    auto sideNormal = [&](float angle) {
        return glm::normalize(glm::vec3(std::cos(angle) * HEIGHT, RADIUS, std::sin(angle) * HEIGHT));
    };

    // Side: base ring (segments + 1 with seam) plus one apex vertex per
    // segment, so each triangle gets a smooth normal and its own apex UV.
    for (int i = 0; i <= segments; ++i) {
        float u = (float)i / segments;
        float angle = u * TWO_PI;
        vertices.push_back({ { std::cos(angle) * RADIUS, 0.0f, std::sin(angle) * RADIUS }, sideNormal(angle), { u, 0.0f } });
    }
    unsigned int firstApex = (unsigned int)vertices.size();
    for (int i = 0; i < segments; ++i) {
        float u = (i + 0.5f) / segments;
        vertices.push_back({ { 0.0f, HEIGHT, 0.0f }, sideNormal(u * TWO_PI), { u, 1.0f } });
    }
    for (int i = 0; i < segments; ++i) {
        indices.insert(indices.end(), { (unsigned int)i, firstApex + i, (unsigned int)i + 1 });
    }

    // Base cap facing down
    unsigned int center = (unsigned int)vertices.size();
    vertices.push_back({ { 0, 0, 0 }, { 0, -1, 0 }, { 0.5f, 0.5f } });
    for (int i = 0; i <= segments; ++i) {
        float angle = (float)i / segments * TWO_PI;
        glm::vec2 ring(std::cos(angle), std::sin(angle));
        vertices.push_back({ { ring.x * RADIUS, 0.0f, ring.y * RADIUS }, { 0, -1, 0 }, ring * 0.5f + 0.5f });
    }
    for (int i = 0; i < segments; ++i) {
        indices.insert(indices.end(), { center, center + 1 + i, center + 2 + i });
    }
    return uploadMesh(vertices, indices);
}

void deleteMesh(Mesh &mesh) {
    glDeleteVertexArrays(1, &mesh.vao);
    glDeleteBuffers(1, &mesh.vbo);
    glDeleteBuffers(1, &mesh.ebo);
    mesh = Mesh();
}

// ------------------------------------------------------------------------------
// Textures
// ------------------------------------------------------------------------------

// Load one image file into a mipmapped texture; returns 0 on failure
GLuint loadTexture(const TextureFile &file) {
    int width = 0, height = 0, channels = 0;
    // Image rows are stored top-first; OpenGL expects the bottom row first
    stbi_set_flip_vertically_on_load(true);
    unsigned char *pixels = stbi_load(file.path, &width, &height, &channels, STBI_rgb_alpha);
    if (pixels == nullptr) {
        std::cerr << "Failed to load texture '" << file.path << "': " << stbi_failure_reason()
                  << "\n(run the program from the folder that contains textures/)\n";
        return 0;
    }

    GLuint texture = 0;
    glGenTextures(1, &texture);
    glBindTexture(GL_TEXTURE_2D, texture);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, file.wrapMode);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, file.wrapMode);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    // Rows of 4-byte RGBA pixels are always 4-byte aligned, the GL default
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels);
    glGenerateMipmap(GL_TEXTURE_2D);

    stbi_image_free(pixels);
    return texture;
}

// ------------------------------------------------------------------------------
// Castle construction (hierarchical modeling)
//
// Each builder receives its parent's transform and appends parts expressed
// relative to it. Transforms compose as parent * translate * rotate * scale.
// ------------------------------------------------------------------------------

// Append a box of the given size, centered at `center` in the parent's space
void addBox(std::vector<Part> &parts, const glm::mat4 &parent, glm::vec3 center, glm::vec3 size,
            TextureId texture, glm::vec3 tint = NO_TINT, float yawDegrees = 0.0f) {
    glm::mat4 transform = glm::translate(parent, center);
    transform = glm::rotate(transform, glm::radians(yawDegrees), glm::vec3(0, 1, 0));
    transform = glm::scale(transform, size);
    parts.push_back({ Shape::Box, texture, transform, size, tint, true, glm::vec2(1.0f) });
}

// Append a cylinder or cone standing on `base` (mesh UVs, tiled by texScale)
void addRound(std::vector<Part> &parts, const glm::mat4 &parent, Shape shape, glm::vec3 base,
              float radius, float height, TextureId texture, glm::vec2 texScale) {
    glm::vec3 size(radius * 2.0f, height, radius * 2.0f);
    glm::mat4 transform = glm::scale(glm::translate(parent, base), size);
    parts.push_back({ shape, texture, transform, size, NO_TINT, false, texScale });
}

// Row of merlons (battlement teeth) from `start` to `end` on a wall top.
// Pass includeEnd = false when the next row starts where this one ends, so
// the shared corner merlon is not drawn twice.
void addBattlement(std::vector<Part> &parts, const glm::mat4 &parent, glm::vec3 start, glm::vec3 end,
                   bool includeEnd = true) {
    glm::vec3 span = end - start;
    int count = (int)(glm::length(span) / MERLON_SPACING) + 1;
    int placed = (includeEnd || count == 1) ? count : count - 1;
    for (int i = 0; i < placed; ++i) {
        float t = (count == 1) ? 0.5f : (float)i / (count - 1);
        glm::vec3 position = start + span * t + glm::vec3(0.0f, MERLON_HEIGHT * 0.5f, 0.0f);
        addBox(parts, parent, position, glm::vec3(MERLON_SIZE, MERLON_HEIGHT, MERLON_SIZE), TEX_STONE);
    }
}

// Flag pole with a banner, standing on `base`
void addFlag(std::vector<Part> &parts, const glm::mat4 &parent, glm::vec3 base, float poleHeight) {
    const float POLE_WIDTH = 0.05f;
    const glm::vec3 BANNER_SIZE(0.62f, 0.38f, 0.03f);
    addBox(parts, parent, base + glm::vec3(0.0f, poleHeight * 0.5f, 0.0f),
           glm::vec3(POLE_WIDTH, poleHeight, POLE_WIDTH), TEX_WOOD, glm::vec3(0.55f));

    // The banner shows the whole banner image on its faces (no box mapping)
    glm::vec3 bannerCenter = base + glm::vec3(BANNER_SIZE.x * 0.5f + POLE_WIDTH * 0.5f,
                                              poleHeight - BANNER_SIZE.y * 0.5f, 0.0f);
    glm::mat4 transform = glm::scale(glm::translate(parent, bannerCenter), BANNER_SIZE);
    parts.push_back({ Shape::Box, TEX_BANNER, transform, BANNER_SIZE, NO_TINT, false, glm::vec2(1.0f) });
}

// Dark window recess on a wall; `yawDegrees` turns it to face outward
void addWindow(std::vector<Part> &parts, const glm::mat4 &parent, glm::vec3 center,
               glm::vec2 size, float yawDegrees) {
    const glm::vec3 WINDOW_TINT(0.10f, 0.09f, 0.08f);
    addBox(parts, parent, center, glm::vec3(size.x, size.y, 0.06f), TEX_STONE, WINDOW_TINT, yawDegrees);
}

// Round corner tower with slit window, conical roof and flag
void addTower(std::vector<Part> &parts, const glm::mat4 &castle, glm::vec3 base) {
    // The tower's own frame, turned so its local +Z faces away from the keep
    float outwardYaw = glm::degrees(std::atan2(base.x, base.z));
    glm::mat4 tower = glm::rotate(glm::translate(castle, base), glm::radians(outwardYaw), glm::vec3(0, 1, 0));

    const float stoneRepeatsAround = 3.0f; // bricks around the circumference
    addRound(parts, tower, Shape::Cylinder, glm::vec3(0.0f), TOWER_RADIUS, TOWER_HEIGHT, TEX_STONE,
             glm::vec2(stoneRepeatsAround, TOWER_HEIGHT * TEXTURE_REPEATS_PER_UNIT));
    addRound(parts, tower, Shape::Cone, glm::vec3(0.0f, TOWER_HEIGHT, 0.0f), TOWER_ROOF_RADIUS,
             TOWER_ROOF_HEIGHT, TEX_ROOF, glm::vec2(4.0f, 2.0f));
    addWindow(parts, tower, glm::vec3(0.0f, TOWER_HEIGHT * 0.62f, TOWER_RADIUS), glm::vec2(0.14f, 0.42f), 0.0f);
    addFlag(parts, tower, glm::vec3(0.0f, TOWER_HEIGHT + TOWER_ROOF_HEIGHT - 0.05f, 0.0f), 0.75f);
}

// Straight curtain wall between two tower centers, with battlements
void addCurtainWall(std::vector<Part> &parts, const glm::mat4 &castle, glm::vec3 from, glm::vec3 to) {
    glm::vec3 direction = to - from;
    float length = glm::length(direction);
    float yaw = glm::degrees(std::atan2(direction.z, direction.x));
    glm::mat4 wall = glm::rotate(glm::translate(castle, (from + to) * 0.5f), glm::radians(-yaw), glm::vec3(0, 1, 0));

    addBox(parts, wall, glm::vec3(0.0f, WALL_HEIGHT * 0.5f, 0.0f),
           glm::vec3(length, WALL_HEIGHT, WALL_THICKNESS), TEX_STONE);

    // Merlons on the outer edge only; the towers cover both wall ends
    float usable = length * 0.5f - TOWER_RADIUS - MERLON_SIZE;
    float outerEdge = WALL_THICKNESS * 0.5f - MERLON_SIZE * 0.5f;
    addBattlement(parts, wall, glm::vec3(-usable, WALL_HEIGHT, outerEdge), glm::vec3(usable, WALL_HEIGHT, outerEdge));
}

// Gatehouse on the front wall: raised block, wooden gate, path outward
void addGatehouse(std::vector<Part> &parts, const glm::mat4 &castle, glm::vec3 frontCenter) {
    const glm::vec3 BLOCK_SIZE(1.9f, 2.5f, 0.9f);
    const glm::vec3 GATE_SIZE(1.0f, 1.35f, 0.08f);
    glm::mat4 gatehouse = glm::translate(castle, frontCenter);

    addBox(parts, gatehouse, glm::vec3(0.0f, BLOCK_SIZE.y * 0.5f, 0.0f), BLOCK_SIZE, TEX_STONE);
    addBox(parts, gatehouse, glm::vec3(0.0f, GATE_SIZE.y * 0.5f, BLOCK_SIZE.z * 0.5f + GATE_SIZE.z * 0.5f),
           GATE_SIZE, TEX_WOOD);
    addWindow(parts, gatehouse, glm::vec3(0.0f, BLOCK_SIZE.y * 0.74f, BLOCK_SIZE.z * 0.5f), glm::vec2(0.5f, 0.28f), 0.0f);

    float halfWidth = BLOCK_SIZE.x * 0.5f - MERLON_SIZE * 0.5f;
    float frontEdge = BLOCK_SIZE.z * 0.5f - MERLON_SIZE * 0.5f;
    addBattlement(parts, gatehouse, glm::vec3(-halfWidth, BLOCK_SIZE.y, frontEdge),
                  glm::vec3(halfWidth, BLOCK_SIZE.y, frontEdge));

    // Dirt path from the gate to the island's rim: the rim point at the
    // path's outer corners (x = half width) lies at z = sqrt(R^2 - x^2)
    const float PATH_WIDTH = 1.1f;
    const float rimZ = std::sqrt(ISLAND_RADIUS * ISLAND_RADIUS - 0.25f * PATH_WIDTH * PATH_WIDTH);
    const float PATH_LENGTH = rimZ - (frontCenter.z + BLOCK_SIZE.z * 0.5f);
    addBox(parts, gatehouse, glm::vec3(0.0f, 0.005f, BLOCK_SIZE.z * 0.5f + PATH_LENGTH * 0.5f),
           glm::vec3(PATH_WIDTH, 0.01f, PATH_LENGTH), TEX_DIRT);
}

// Central keep: tall block with windows, battlements and a roofed turret
void addKeep(std::vector<Part> &parts, const glm::mat4 &castle) {
    const float half = KEEP_WIDTH * 0.5f;
    addBox(parts, castle, glm::vec3(0.0f, KEEP_HEIGHT * 0.5f, 0.0f),
           glm::vec3(KEEP_WIDTH, KEEP_HEIGHT, KEEP_WIDTH), TEX_STONE);

    // Two windows on each of the four faces, turned to face outward
    for (int side = 0; side < 4; ++side) {
        float yaw = 90.0f * side;
        glm::mat4 face = glm::rotate(castle, glm::radians(yaw), glm::vec3(0, 1, 0));
        for (float x : { -0.5f, 0.5f }) {
            addWindow(parts, face, glm::vec3(x, KEEP_HEIGHT * 0.66f, half), glm::vec2(0.28f, 0.5f), 0.0f);
        }
        // Battlement along this face's top outer edge; its end corner is the
        // next face's start corner, so each face leaves that merlon out
        float edge = half - MERLON_SIZE * 0.5f;
        addBattlement(parts, face, glm::vec3(-edge, KEEP_HEIGHT, edge), glm::vec3(edge, KEEP_HEIGHT, edge), false);
    }

    // Turret rising from the keep's roof
    const float TURRET_RADIUS = 0.5f;
    const float TURRET_HEIGHT = 1.1f;
    addRound(parts, castle, Shape::Cylinder, glm::vec3(0.0f, KEEP_HEIGHT, 0.0f), TURRET_RADIUS, TURRET_HEIGHT,
             TEX_STONE, glm::vec2(2.0f, TURRET_HEIGHT * TEXTURE_REPEATS_PER_UNIT));
    addRound(parts, castle, Shape::Cone, glm::vec3(0.0f, KEEP_HEIGHT + TURRET_HEIGHT, 0.0f), 0.68f, 1.2f,
             TEX_ROOF, glm::vec2(3.0f, 1.5f));
    addFlag(parts, castle, glm::vec3(0.0f, KEEP_HEIGHT + TURRET_HEIGHT + 1.15f, 0.0f), 0.95f);
}

// Build the complete castle in castle space (origin = island center, y = 0
// = ground level). The animated turntable rotation is applied at draw time.
std::vector<Part> buildCastle() {
    std::vector<Part> parts;
    const glm::mat4 castle(1.0f);
    const float s = WALL_HALF_SPAN;

    // Round island: an earth base topped by a thin grass layer whose top
    // surface is y = 0. Both reuse the cylinder mesh.
    const float EARTH_DEPTH = 0.5f;
    const float GRASS_DEPTH = 0.03f;
    const float islandRepeats = ISLAND_RADIUS * 2.0f * TEXTURE_REPEATS_PER_UNIT;
    addRound(parts, castle, Shape::Cylinder, glm::vec3(0.0f, -EARTH_DEPTH, 0.0f), ISLAND_RADIUS,
             EARTH_DEPTH - GRASS_DEPTH, TEX_DIRT, glm::vec2(12.0f, 0.5f));
    addRound(parts, castle, Shape::Cylinder, glm::vec3(0.0f, -GRASS_DEPTH, 0.0f), ISLAND_RADIUS,
             GRASS_DEPTH, TEX_GRASS, glm::vec2(islandRepeats));

    // Corner towers, clockwise from front-left as seen by the camera at start
    const glm::vec3 corners[] = { { -s, 0, s }, { s, 0, s }, { s, 0, -s }, { -s, 0, -s } };
    for (int i = 0; i < 4; ++i) {
        addCurtainWall(parts, castle, corners[i], corners[(i + 1) % 4]);
    }
    for (const glm::vec3 &corner : corners) {
        addTower(parts, castle, corner);
    }

    addGatehouse(parts, castle, glm::vec3(0.0f, 0.0f, s));
    addKeep(parts, castle);
    return parts;
}

// ------------------------------------------------------------------------------
// Shader program
// ------------------------------------------------------------------------------

// Compile one shader stage; returns 0 and prints the log on failure
GLuint compileShader(GLenum stage, const char *source, const char *stageName) {
    GLuint shader = glCreateShader(stage);
    glShaderSource(shader, 1, &source, nullptr);
    glCompileShader(shader);

    GLint success = GL_FALSE;
    glGetShaderiv(shader, GL_COMPILE_STATUS, &success);
    if (!success) {
        char log[1024];
        glGetShaderInfoLog(shader, sizeof(log), nullptr, log);
        std::cerr << stageName << " shader compilation failed:\n" << log << "\n";
        glDeleteShader(shader);
        return 0;
    }
    return shader;
}

// Compile and link the shader program; returns 0 on failure
GLuint createShaderProgram() {
    GLuint vertexShader   = compileShader(GL_VERTEX_SHADER, VERTEX_SHADER_SOURCE, "Vertex");
    GLuint fragmentShader = compileShader(GL_FRAGMENT_SHADER, FRAGMENT_SHADER_SOURCE, "Fragment");
    if (vertexShader == 0 || fragmentShader == 0) {
        glDeleteShader(vertexShader);
        glDeleteShader(fragmentShader);
        return 0;
    }

    GLuint program = glCreateProgram();
    glAttachShader(program, vertexShader);
    glAttachShader(program, fragmentShader);
    glLinkProgram(program);
    glDeleteShader(vertexShader);
    glDeleteShader(fragmentShader);

    GLint success = GL_FALSE;
    glGetProgramiv(program, GL_LINK_STATUS, &success);
    if (!success) {
        char log[1024];
        glGetProgramInfoLog(program, sizeof(log), nullptr, log);
        std::cerr << "Shader program linking failed:\n" << log << "\n";
        glDeleteProgram(program);
        return 0;
    }
    return program;
}

// Uniform locations looked up once after linking
struct Uniforms {
    GLint model, normalMatrix, view, projection;
    GLint boxMapping, partSize, repeatsPerUnit, texScale;
    GLint texture, tint, sunDirection, sunColor, skyAmbient, groundAmbient;
};

Uniforms findUniforms(GLuint program) {
    Uniforms u;
    u.model          = glGetUniformLocation(program, "uModel");
    u.normalMatrix   = glGetUniformLocation(program, "uNormalMatrix");
    u.view           = glGetUniformLocation(program, "uView");
    u.projection     = glGetUniformLocation(program, "uProjection");
    u.boxMapping     = glGetUniformLocation(program, "uBoxMapping");
    u.partSize       = glGetUniformLocation(program, "uPartSize");
    u.repeatsPerUnit = glGetUniformLocation(program, "uRepeatsPerUnit");
    u.texScale       = glGetUniformLocation(program, "uTexScale");
    u.texture        = glGetUniformLocation(program, "uTexture");
    u.tint           = glGetUniformLocation(program, "uTint");
    u.sunDirection   = glGetUniformLocation(program, "uSunDirection");
    u.sunColor       = glGetUniformLocation(program, "uSunColor");
    u.skyAmbient     = glGetUniformLocation(program, "uSkyAmbient");
    u.groundAmbient  = glGetUniformLocation(program, "uGroundAmbient");
    return u;
}

// ------------------------------------------------------------------------------
// Rendering
// ------------------------------------------------------------------------------

// Draw every part under the animated root (turntable) transform
void drawCastle(const std::vector<Part> &parts, const Mesh meshes[], const GLuint textures[],
                const Uniforms &u, const glm::mat4 &root) {
    for (const Part &part : parts) {
        const Mesh &mesh = meshes[(int)part.shape];
        glm::mat4 model = root * part.transform;
        // Inverse-transpose keeps normals perpendicular under non-uniform scale
        glm::mat3 normalMatrix = glm::transpose(glm::inverse(glm::mat3(model)));

        glUniformMatrix4fv(u.model, 1, GL_FALSE, glm::value_ptr(model));
        glUniformMatrix3fv(u.normalMatrix, 1, GL_FALSE, glm::value_ptr(normalMatrix));
        glUniform1i(u.boxMapping, part.boxMapping ? 1 : 0);
        glUniform3fv(u.partSize, 1, glm::value_ptr(part.size));
        glUniform2fv(u.texScale, 1, glm::value_ptr(part.texScale));
        glUniform3fv(u.tint, 1, glm::value_ptr(part.tint));
        glBindTexture(GL_TEXTURE_2D, textures[part.texture]);

        glBindVertexArray(mesh.vao);
        glDrawElements(GL_TRIANGLES, mesh.indexCount, GL_UNSIGNED_INT, (void *)0);
    }
    glBindVertexArray(0);
}

// ------------------------------------------------------------------------------
// Window callbacks
// ------------------------------------------------------------------------------

void framebufferSizeCallback(GLFWwindow *, int width, int height) {
    glViewport(0, 0, width, height);
}

void glfwErrorCallback(int code, const char *description) {
    std::cerr << "GLFW error " << code << ": " << description << "\n";
}

void processInput(GLFWwindow *window) {
    if (glfwGetKey(window, GLFW_KEY_ESCAPE) == GLFW_PRESS) {
        glfwSetWindowShouldClose(window, GLFW_TRUE);
    }
}

// ------------------------------------------------------------------------------
// Main
// ------------------------------------------------------------------------------

int main() {
    glfwSetErrorCallback(glfwErrorCallback);
    if (!glfwInit()) {
        std::cerr << "Failed to initialize GLFW\n";
        return EXIT_FAILURE;
    }

    // Request an OpenGL 3.3 core profile context with 4x multisampling
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_SAMPLES, 4);
#ifdef __APPLE__
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
#endif

    GLFWwindow *window = glfwCreateWindow(WINDOW_WIDTH, WINDOW_HEIGHT, WINDOW_TITLE, nullptr, nullptr);
    if (window == nullptr) {
        std::cerr << "Failed to create GLFW window\n";
        glfwTerminate();
        return EXIT_FAILURE;
    }
    glfwMakeContextCurrent(window);
    glfwSetFramebufferSizeCallback(window, framebufferSizeCallback);
    glfwSwapInterval(1);

    if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)) {
        std::cerr << "Failed to initialize GLAD\n";
        glfwDestroyWindow(window);
        glfwTerminate();
        return EXIT_FAILURE;
    }

    GLuint program = createShaderProgram();
    GLuint textures[TEXTURE_COUNT] = {};
    bool texturesLoaded = true;
    for (int i = 0; i < TEXTURE_COUNT && program != 0; ++i) {
        textures[i] = loadTexture(TEXTURE_FILES[i]);
        texturesLoaded = texturesLoaded && textures[i] != 0;
    }
    if (program == 0 || !texturesLoaded) {
        glDeleteTextures(TEXTURE_COUNT, textures);
        glDeleteProgram(program);
        glfwDestroyWindow(window);
        glfwTerminate();
        return EXIT_FAILURE;
    }

    // Indexed by Shape: Box, Cylinder, Cone
    Mesh meshes[] = { createBoxMesh(), createCylinderMesh(ROUND_SEGMENTS), createConeMesh(ROUND_SEGMENTS) };
    const std::vector<Part> parts = buildCastle();

    glEnable(GL_DEPTH_TEST);
    glEnable(GL_CULL_FACE);
    glEnable(GL_MULTISAMPLE);

    // Camera and lighting never change, so their uniforms are set once
    glUseProgram(program);
    Uniforms u = findUniforms(program);
    glm::mat4 view = glm::lookAt(CAMERA_POSITION, CAMERA_TARGET, CAMERA_UP);
    glUniformMatrix4fv(u.view, 1, GL_FALSE, glm::value_ptr(view));
    glm::vec3 sunDirection = glm::normalize(SUN_DIRECTION);
    glUniform3fv(u.sunDirection, 1, glm::value_ptr(sunDirection));
    glUniform3fv(u.sunColor, 1, glm::value_ptr(SUN_COLOR));
    glUniform3fv(u.skyAmbient, 1, glm::value_ptr(SKY_AMBIENT));
    glUniform3fv(u.groundAmbient, 1, glm::value_ptr(GROUND_AMBIENT));
    glUniform1f(u.repeatsPerUnit, TEXTURE_REPEATS_PER_UNIT);
    glUniform1i(u.texture, 0);
    glActiveTexture(GL_TEXTURE0);

    while (!glfwWindowShouldClose(window)) {
        processInput(window);

        // Rebuild the projection each frame so resizing keeps the castle
        // centered and undistorted; skip rendering while minimized.
        int framebufferWidth = 0;
        int framebufferHeight = 0;
        glfwGetFramebufferSize(window, &framebufferWidth, &framebufferHeight);
        if (framebufferWidth > 0 && framebufferHeight > 0) {
            float aspect = (float)framebufferWidth / (float)framebufferHeight;
            glm::mat4 projection = glm::perspective(glm::radians(FIELD_OF_VIEW_DEG), aspect,
                                                    NEAR_PLANE, FAR_PLANE);
            glUniformMatrix4fv(u.projection, 1, GL_FALSE, glm::value_ptr(projection));

            glClearColor(SKY_COLOR.r, SKY_COLOR.g, SKY_COLOR.b, 1.0f);
            glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

            // Root of the hierarchy: the turntable spin applied to every part
            float angle = glm::radians(ROTATION_DEGREES_PER_SECOND * (float)glfwGetTime());
            glm::mat4 root = glm::rotate(glm::mat4(1.0f), angle, glm::vec3(0, 1, 0));
            drawCastle(parts, meshes, textures, u, root);
        }

        glfwSwapBuffers(window);
        glfwPollEvents();
    }

    for (Mesh &mesh : meshes) {
        deleteMesh(mesh);
    }
    glDeleteTextures(TEXTURE_COUNT, textures);
    glDeleteProgram(program);
    glfwDestroyWindow(window);
    glfwTerminate();
    return EXIT_SUCCESS;
}
